# Generated by Django 4.2.11 on 2026-06-03 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lecturers_students_delete_student_alter_user_options_and_more'),
        ('attendance', '0002_attendancehistory_cameras_facelogs_and_more'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ClassID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassCode', models.CharField(max_length=20, unique=True)),
                ('ClassName', models.CharField(max_length=100)),
                ('Lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.lecturers')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
            options={
                'unique_together': {('Student', 'Class')},
            },
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='account',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='ClassSession',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
