# Generated by Django 4.2.11 on 2026-06-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lecturers_students_delete_student_alter_user_options_and_more'),
        ('classes', '0002_class_studentclass_remove_classsession_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='DayOfWeek',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='EndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='EndTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='StartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='StartTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='Lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.lecturers'),
        ),
    ]
