# Generated by Django 4.2.11 on 2026-06-03 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lecturers_students_delete_student_alter_user_options_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceHistory',
            fields=[
                ('AttendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('AttendanceDate', models.DateField()),
                ('CheckInTime', models.DateTimeField()),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('CameraID', models.AutoField(primary_key=True, serialize=False)),
                ('CameraName', models.CharField(max_length=100)),
                ('CameraURL', models.CharField(blank=True, max_length=500, null=True)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facelogs',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('DetectTime', models.DateTimeField()),
                ('Confidence', models.FloatField()),
                ('ImagePath', models.CharField(max_length=255)),
                ('Camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.cameras')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
