# Generated by Django 4.2.11 on 2026-06-03 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lecturers_students_delete_student_alter_user_options_and_more'),
        ('classes', '0002_class_studentclass_remove_classsession_schedule_and_more'),
        ('attendance', '0002_attendancehistory_cameras_facelogs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancehistory',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
        migrations.AddField(
            model_name='attendancehistory',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students'),
        ),
    ]
